# Specify the version for docker-compose.yml
version: "1"

# add the serivces needed (postgres,go)
services:
  postgres:
    image: postgres:16.4
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  go:
    build:
      context: ./backend
    depends_on:
      - "postgres"
    ports:
      - 3000:80
    env_file:
      - .env
    volumes:
      - /app/files
      
  react:
    build:
      context: ./frontend
    ports:
      - 4200:80
    env_file:
      - .env
volumes:
  dbdata: # create the volume for persisting data.
            