# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: database
    image: postgres:16.4
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: ./
    depends_on:
      - "postgres"
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - /app/files
      
  #react:
  #  container_name: react
  #  build:
  #    context: ./frontend
  #  ports:
  #    - 4200:80
  #  env_file:
  #    - .env
volumes:
  dbdata: # create the volume for persisting data.
            