name: Go Build

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - master  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'  # Specify your Go version here

      - name: Install dependencies
        run: go mod download
        working-directory: backend

      - name: Build
        run: go build
        working-directory: backend

     # - name: Run tests (optional)
     #   run: go test -v ./...
