name: backend build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'
      - name: Install dependencies
        run: go mod download
        working-directory: backend
      - name: Build
        run: go build
        working-directory: backend
      - name: Test
        run: go test ./*
        working-directory: backend/test
